name: Daily Mock Finance Update

on:
  schedule:
    - cron: '10 10 * * *'  # Runs every day at 12:20 PM UTC
  workflow_dispatch:  # Allows manual trigger from GitHub Actions

jobs:
  run-script:
    runs-on: ubuntu-latest  # Using GitHub's Linux server

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Use Python 3.10

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the Python Script
        run: |
          source venv/bin/activate
          python daily_mock_retail_data.py
